flowchart LR

subgraph 0["src"]
subgraph 1["app"]
2["layout.tsx"]
6["manifest.ts"]
9["manifest.test.ts"]
A["page.tsx"]
subgraph Z["timer"]
10["page.tsx"]
end
end
subgraph 3["client"]
subgraph 4["styles"]
5["globals.css"]
end
subgraph 7["components"]
8["loading-page.tsx"]
B["router.tsx"]
D["home-page.tsx"]
E["timer-form.tsx"]
N["timer-page.tsx"]
subgraph O["ui"]
P["link.tsx"]
16["button.tsx"]
end
Q["visual-timer.tsx"]
11["home-page.test.tsx"]
12["loading-page.test.tsx"]
13["router.test.tsx"]
14["timer-form.test.tsx"]
15["timer-page.test.tsx"]
18["visual-timer.test.tsx"]
end
F["nav.ts"]
G["routes.ts"]
H["db.ts"]
subgraph K["hooks"]
L["useUserId.ts"]
R["sync.ts"]
end
19["db.test.ts"]
1A["nav.test.ts"]
end
subgraph I["lib"]
J["error.ts"]
M["time.ts"]
17["utils.ts"]
end
subgraph S["server"]
subgraph T["actions"]
U["index.ts"]
end
subgraph V["db"]
W["schema.ts"]
X["index.ts"]
end
Y["env.ts"]
end
1B["test-setup.ts"]
end
C["assert"]
2-->6
2-->8
2-->5
9-->6
A-->B
B-->D
B-->N
B-->H
B-->R
B-->L
B-->F
B-->G
B-->M
B-->C
D-->E
E-->F
E-->H
E-->L
E-->J
E-->M
F-->G
F-->H
F-->G
F-->J
N-->H
N-->P
N-->Q
N-->J
N-->M
P-->F
P-->G
R-->L
R-->H
R-->J
R-->M
R-->U
U-->W
U-->X
X-->W
X-->Y
10-->B
10-->M
11-->D
12-->8
13-->B
13-->M
14-->E
15-->N
15-->M
16-->17
18-->Q
19-->H
1A-->F
1B-->H
1B-->C
