flowchart LR

subgraph 0["src"]
subgraph 1["app"]
2["layout.tsx"]
6["manifest.ts"]
9["page.tsx"]
subgraph X["timer"]
Y["page.tsx"]
end
end
subgraph 3["client"]
subgraph 4["styles"]
5["globals.css"]
end
subgraph 7["components"]
8["loading-page.tsx"]
A["router.tsx"]
R["home-page.tsx"]
S["timer-form.tsx"]
T["timer-page.tsx"]
subgraph U["ui"]
V["link.tsx"]
13["button.tsx"]
end
W["visual-timer.tsx"]
Z["home-page.test.tsx"]
10["router.test.tsx"]
11["timer-form.test.tsx"]
12["timer-page.test.tsx"]
15["visual-timer.test.tsx"]
end
subgraph C["hooks"]
D["sync.ts"]
E["useUserId.ts"]
end
F["db.ts"]
Q["nav.ts"]
end
subgraph G["lib"]
H["error.ts"]
I["time.ts"]
14["utils.ts"]
end
subgraph J["server"]
subgraph K["actions"]
L["index.ts"]
end
subgraph M["db"]
N["schema.ts"]
O["index.ts"]
end
P["env.ts"]
end
16["test-setup.ts"]
end
B["assert"]
2-->6
2-->8
2-->5
9-->A
A-->D
A-->E
A-->Q
A-->R
A-->8
A-->T
A-->F
A-->B
D-->E
D-->F
D-->H
D-->I
D-->L
L-->N
L-->O
O-->N
O-->P
Q-->A
Q-->F
Q-->H
R-->S
S-->Q
S-->F
S-->E
S-->H
S-->I
T-->F
T-->E
T-->V
T-->W
T-->H
T-->I
V-->A
V-->Q
Y-->A
Y-->I
Z-->R
10-->A
10-->I
11-->S
12-->T
12-->I
13-->14
15-->W
16-->B
